### Home page
GET  http://localhost:6969 HTTP/1.1

###
POST http://localhost:6969/create HTTP/1.1
Content-Type: application/json

{
  "color": "black"
}


### Join game
POST http://localhost:6969/game/278C1F4833DB4700978F7D8CA87010F9 HTTP/1.1

